### ISSUE TITLE
Standardization

### ISSUE THREAD

**Issue by fbordignon** [LukasMosser/digital_rocks_data#6]
Great work on this library! I am interested in integrating the download into [GeoSlicer ](https://www.ltrace.com.br/geoslicer/) with an auto-generated GUI. But for that, we would propose some type of standarization of the METADATA and download process via virtual functions implemented by each dataset. Would that be something that you guys believe could be integrated? I believe we can define an easy to follow standard now that there are a few datasets.
Soon GeoSlicer will be published as opensource as well, so we can all benefit from this integration!

**Comment by fbordignon** [comment]
Good news, GeoSlicer is now open source! Check it out https://github.com/petrobras/GeoSlicer
We are adding a module for drd as is, so users can download and load the images directly into GeoSlicer. However, it has a lot of things hard coded and some level of standarization could help a lot in keeping things updated!

Thanks!

**Comment by LukasMosser** [comment]
Hey @fbordignon, I'm glad to hear you find this useful!

Technically I am the only maintainer of the project so "we" would be happy have input on improving the codebase including METADATA and more standardization.

What do you think would be the best way, is it something you could propose through a pull request or should we have an online discussion about it first?

/L

**Comment by fbordignon** [comment]
@LukasMosser thanks for your reply. We are definitely working on this. The idea is to generate metadata to automate the listing and downloading of the datasets. I am assigning this issue to someone in our team. We will likely generate a pull request and we can discuss/work based on it. Is that good?
Regards

**Comment by LukasMosser** [comment]
Sounds good to me!
